### ISSUE TITLE
Craft recipe causes unintentional tool repair.

### ISSUE THREAD

**Issue by jhcole** [FozLand/farming_plus#1]
The `farming:pumpkin_face` recipe also repairs the axe. There are likely other recipes with the same problem.

**Comment by mootpoint** [comment]
How bout a new item called carving knife that acts like column planner used only to carve pumpkins

**Comment by mootpoint** [comment]
Craft recipe not needed. Hit pumpkin with sword makes pumpkin face. Does not repair sword. Maybe comment out recipe
